version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minigame-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    # 운영 기본 커맨드(이미 Dockerfile CMD에 있으므로 생략 가능)
    command: [ "gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "minigame:create_app()" ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/').getcode()==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["prod"]

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minigame-app-dev
    env_file:
      - .env
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/').getcode()==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 5
    profiles: ["dev"]
